services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-demo}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped

  prices-provider:
    container_name: prices_provider_container
    build:
      context: ./projects/prices-provider
      dockerfile: Dockerfile
    entrypoint: "node ./dist/index.js ${BYBIT_API_KEY} ${BYBIT_API_SECRET}"
    environment:
      DB_HOST: postgres
      DB_PORT: ${POSTGRES_PORT:-5432}
      DB_NAME: ${POSTGRES_DBNAME:-crypto_prices}
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-demo}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_USER_TOKEN: ${TELEGRAM_USER_TOKEN}
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - postgres
volumes:
  postgres: